
// THIS FILE IS AUTOGENERATED WHEN PAGES ARE UPDATED
import { lazy } from "react";
import { RouteObject } from "react-router";


import { UserGuard } from "app";


const App = lazy(() => import("./pages/App.tsx"));
const History = lazy(() => import("./pages/History.tsx"));
const Login = lazy(() => import("./pages/Login.tsx"));
const Logout = lazy(() => import("./pages/Logout.tsx"));
const Results = lazy(() => import("./pages/Results.tsx"));
const Study = lazy(() => import("./pages/Study.tsx"));

export const userRoutes: RouteObject[] = [

	{ path: "/", element: <App />},
	{ path: "/history", element: <UserGuard><History /></UserGuard>},
	{ path: "/login", element: <Login />},
	{ path: "/logout", element: <UserGuard><Logout /></UserGuard>},
	{ path: "/results", element: <UserGuard><Results /></UserGuard>},
	{ path: "/study", element: <UserGuard><Study /></UserGuard>},

];
